# Generated by Django 5.0.1 on 2026-01-06 10:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PolicyFramework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("framework_name", models.CharField(max_length=255)),
                (
                    "framework_type",
                    models.CharField(
                        choices=[
                            ("national", "National Law"),
                            ("international", "International Standard"),
                            ("institutional", "Institutional Policy"),
                            ("sdg", "SDG Alignment"),
                            ("wcag", "WCAG Guideline"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                (
                    "reference_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "policy_frameworks",
            },
        ),
        migrations.CreateModel(
            name="PolicyRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation_title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("target_audience", models.CharField(max_length=255)),
                ("implementation_steps", models.TextField()),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="policy_guidance.policyframework",
                    ),
                ),
            ],
            options={
                "db_table": "policy_recommendations",
            },
        ),
    ]
