# Generated by Django 5.0.1 on 2026-01-06 10:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("classification", "Classification"),
                            ("detection", "Detection"),
                            ("prediction", "Prediction"),
                            ("recommendation", "Recommendation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("file_path", models.FileField(upload_to="ml_models/")),
                ("description", models.TextField()),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("training_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ml_models",
            },
        ),
        migrations.CreateModel(
            name="TrainingDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("file_path", models.FileField(upload_to="datasets/")),
                ("total_records", models.IntegerField(default=0)),
                ("features_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "training_datasets",
            },
        ),
        migrations.CreateModel(
            name="ModelPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("accuracy", models.DecimalField(decimal_places=2, max_digits=5)),
                ("precision", models.DecimalField(decimal_places=2, max_digits=5)),
                ("recall", models.DecimalField(decimal_places=2, max_digits=5)),
                ("f1_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("metrics_data", models.JSONField(default=dict)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to="ai_engine.mlmodel",
                    ),
                ),
            ],
            options={
                "db_table": "model_performance",
            },
        ),
    ]
