# Generated by Django 5.0.1 on 2026-01-06 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessibilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_id", models.CharField(max_length=50, unique=True)),
                ("wcag_criterion", models.CharField(max_length=50)),
                (
                    "wcag_level",
                    models.CharField(
                        choices=[
                            ("A", "Level A"),
                            ("AA", "Level AA"),
                            ("AAA", "Level AAA"),
                        ],
                        max_length=5,
                    ),
                ),
                ("rule_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("testing_procedure", models.TextField()),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "severity_default",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("serious", "Serious"),
                            ("moderate", "Moderate"),
                            ("minor", "Minor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "accessibility_rules",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("scan", "Scan"),
                            ("export", "Export"),
                        ],
                        max_length=50,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_key", models.CharField(max_length=100, unique=True)),
                ("config_value", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "system_configurations",
            },
        ),
    ]
