# Generated by Django 5.0.1 on 2026-01-06 10:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compliance_evaluation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("compliance", "Compliance Report"),
                            ("trend_analysis", "Trend Analysis"),
                            ("user_testing", "User Testing Report"),
                            ("comparison", "Comparison Report"),
                            ("executive_summary", "Executive Summary"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "report_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("html", "HTML"),
                            ("json", "JSON"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="reports/")),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("report_data", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("total_issues_detected", models.IntegerField(default=0)),
                ("issues_resolved", models.IntegerField(default=0)),
                (
                    "compliance_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "improvement_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("metrics_data", models.JSONField(default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="compliance_evaluation.accessibilityproject",
                    ),
                ),
            ],
            options={
                "db_table": "analytics",
                "ordering": ["-date"],
            },
        ),
    ]
