# Generated by Django 5.0.1 on 2026-01-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_active_user",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="customuser",
            name="notification_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="notification_in_app",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="report_format",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("excel", "Excel"), ("html", "HTML")],
                default="pdf",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("corporate", "Corporate"),
                    ("government", "Government"),
                    ("non_profit", "Non-Profit"),
                    ("education", "Education"),
                    ("healthcare", "Healthcare"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("developer", "Developer"),
                    ("designer", "Designer"),
                    ("content_creator", "Content Creator"),
                    ("auditor", "Auditor"),
                    ("accessibility_advocate", "Accessibility Advocate"),
                    ("policymaker", "Policymaker"),
                    ("researcher", "Researcher"),
                    ("analyst", "Analyst"),
                ],
                default="developer",
                max_length=30,
            ),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table=None,
        ),
        migrations.DeleteModel(
            name="UserPreferences",
        ),
    ]
