# Generated by Django 5.0.1 on 2026-01-06 10:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compliance_evaluation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disability_type",
                    models.CharField(
                        choices=[
                            ("visual", "Visual Impairment"),
                            ("hearing", "Hearing Impairment"),
                            ("motor", "Motor Impairment"),
                            ("cognitive", "Cognitive Impairment"),
                            ("none", "No Disability"),
                            ("multiple", "Multiple Disabilities"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "assistive_technologies",
                    models.TextField(help_text="List of assistive technologies used"),
                ),
                ("testing_experience", models.TextField()),
                ("consent_given", models.BooleanField(default=False)),
                ("consent_date", models.DateTimeField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tester_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "testers",
            },
        ),
        migrations.CreateModel(
            name="TestTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("task_description", models.TextField()),
                ("task_url", models.URLField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tasks",
                        to="user_testing.tester",
                    ),
                ),
            ],
            options={
                "db_table": "test_tasks",
            },
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("very_easy", "Very Easy"),
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("difficult", "Difficult"),
                            ("very_difficult", "Very Difficult"),
                            ("impossible", "Impossible"),
                        ],
                        max_length=50,
                    ),
                ),
                ("accessibility_barriers", models.TextField()),
                ("positive_aspects", models.TextField(blank=True, null=True)),
                ("suggestions", models.TextField(blank=True, null=True)),
                ("time_taken", models.DurationField(blank=True, null=True)),
                (
                    "success_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of task completed",
                        max_digits=5,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="user_testing.testtask",
                    ),
                ),
            ],
            options={
                "db_table": "user_feedback",
            },
        ),
        migrations.CreateModel(
            name="UserTestingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("recruiting", "Recruiting"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("target_testers", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "coordinator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinated_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testing_programs",
                        to="compliance_evaluation.accessibilityproject",
                    ),
                ),
            ],
            options={
                "db_table": "user_testing_programs",
            },
        ),
        migrations.AddField(
            model_name="testtask",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="user_testing.usertestingprogram",
            ),
        ),
    ]
